version: '3'
services:
  echo:
    image: h3poteto/playground-echo-go:master
    environment:
      PORT: 9090
  nginx:
    image: h3poteto/playground-echo-nginx:master
    links:
      - echo:echo
    environment:
      ECHO_SERVER: echo
      ECHO_PORT: 9090
    ports:
      - "80:80"
