apiVersion: v1
kind: Namespace
metadata:
  name: playground-echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
  labels:
    name: echo
  namespace: playground-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: echo
    spec:
      containers:
        - name: echo
          image: h3poteto/playground-echo-go:master
          env:
            - name: PORT
              value: "9090"
        - name: nginx
          image: h3poteto/playground-echo-nginx:master
          ports:
            - containerPort: 80
          env:
            - name: ECHO_SERVER
              value: "127.0.0.1"
            - name: ECHO_PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: playground-echo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: echo

