version: 2
jobs:
  build:
    machine: true
    environment:
      GO_REPOSITORY: h3poteto/playground-echo-go
      NGINX_REPOSITORY: h3poteto/playground-echo-nginx
      CLIENT_REPOSITORY: h3poteto/playground-echo-client
    steps:
      - checkout
      - run:
          name: Build and push
          command: |
            docker login -u $HUB_USER -p $HUB_PASSWORD
            docker build -t $GO_REPOSITORY:$CIRCLE_BRANCH -f dockerfiles/go/Dockerfile .
            docker push $GO_REPOSITORY:$CIRCLE_BRANCH
            docker build -t $NGINX_REPOSITORY:$CIRCLE_BRANCH -f dockerfiles/nginx/Dockerfile .
            docker push $NGINX_REPOSITORY:$CIRCLE_BRANCH
            docker build -t $CLIENT_REPOSITORY:$CIRCLE_BRANCH -f dockerfiles/client/Dockerfile .
            docker push $CLIENT_REPOSITORY:$CIRCLE_BRANCH

